server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    pipeline_stages:
      - regex:
          expression: ^\[(?P<time>\d{4}-\d{2}-\d{2}T\d{1,2}:\d{2}:\d{2}.\d{3})\] \[(?P<level>\S+)\] \S+ - (?P<message>.*)
      - multiline:
          firstline: ^\[(?P<time>\d{4}-\d{2}-\d{2}T\d{1,2}:\d{2}:\d{2}.\d{3})\]
          max_wait_time: 3s
      - labels:
          level:
    static_configs:
    - labels:
        job: myservice
        app: myservice
        applicationType: nodejs
        __path__: /var/log/*log
